// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/serve/{zone_id}": {
            "get": {
                "description": "Returns the first matching ad for the specified zone.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Serve"
                ],
                "summary": "Serve an ad",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Zone ID",
                        "name": "zone_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Ad"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Ad": {
            "type": "object",
            "properties": {
                "ad_type": {
                    "$ref": "#/definitions/models.AdType"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_verified": {
                    "type": "boolean"
                },
                "metadata": {
                    "$ref": "#/definitions/models.AdMetaData"
                },
                "name": {
                    "type": "string"
                },
                "program_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.AdMetaData": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "keyword": {
                    "type": "string"
                }
            }
        },
        "models.AdType": {
            "type": "string",
            "enum": [
                "VIDEO",
                "BANNER",
                "NATIVE"
            ],
            "x-enum-varnames": [
                "AdTypeVideo",
                "AdTypeBanner",
                "AdTypeNative"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "ServeAli API",
	Description:      "Simple ad serving service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
